# Form implementation generated from reading ui file 'App.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
import sonar, Pref2
from PyQt6.QtWidgets import QMessageBox

class MplCanvas(FigureCanvasQTAgg):
    def __init__(self, parent=None, width=10, height=10, dpi=80):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)    

    def Draw(self):

        fig = Figure(figsize=(5, 4), dpi=100)
        self.axes = fig.add_subplot(111)
        self.axes.plot(1,5)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        #self.widget = QtWidgets.QWidget(self.centralwidget)
        #self.widget.setObjectName("widget")
        sc1 = MplCanvas()
        self.horizontalLayout_2.addWidget(sc1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        #self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sc2 = MplCanvas()
        #self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(sc2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setText("")
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setScaledContents(False)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.action.triggered.connect(self.pref)
        self.pushButton.clicked.connect(self.Start)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Тип цели"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Подводная лодка"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Эмитатор лодки"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Облако отражателей"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.label_11.setText(_translate("MainWindow", "Пеленг:"))
        self.label_8.setText(_translate("MainWindow", "Совпадение:"))
        self.label_13.setText(_translate("MainWindow", "Расстояние до цели:"))
        self.menu.setTitle(_translate("MainWindow", "Настройки"))
        self.action.setText(_translate("MainWindow", "Настройки симуляции"))


    def pref(self):

        self.Dialog = QtWidgets.QDialog()
        self.Dialog.setModal(False)
        self.dui = Pref2.Ui_Dialog()
        self.dui.setupUi(self.Dialog)
        self.Dialog.accepted.connect(self.copy)
        self.Dialog.show()
        
    def copy(self):

        self.r = float(self.dui.lineEdit.text())
        self.fb = int(self.dui.lineEdit_2.text())
        self.T = float(self.dui.lineEdit_3.text())
        self.tau = float(self.dui.lineEdit_4.text())
        self.fs = int(self.dui.lineEdit_5.text())
        self.ampl = float(self.dui.lineEdit_6.text())
        self.d = float(self.dui.lineEdit_7.text())

    def Start(self):

        signal = sonar.Simulation(self.fb,self.T,self.tau,self.fs,self.ampl,self.r,self.d,self.comboBox.currentIndex())
        if signal == 1:
            inf = QMessageBox()
            QMessageBox.information(inf,'Error', 'Дальность не должна превышать 3000 м',QMessageBox.StandardButton.Ok)
        else:
           
            sc1 = MplCanvas()
            sc2 = MplCanvas()
            sc1.axes.plot(signal[0],signal[1])
            self.horizontalLayout_2.removeItem(self.horizontalLayout_2.takeAt(0))
            self.horizontalLayout_2.insertWidget(0,sc1)

            sc2.axes.scatter(signal[3],signal[4])
            self.verticalLayout.removeItem(self.verticalLayout.takeAt(0))
            self.verticalLayout.insertWidget(0,sc2)

            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pref()
    sys.exit(app.exec())
